
apiVersion: flightctl.io/v1beta1
kind: Fleet
metadata:
  name: default
spec:
  selector:
    matchLabels:
      fleet: default
  template:
    metadata:
      labels:
        fleet: default
    spec:
      os:
        image: quay.io/{{.metadata.labels.registry}}/my-rhel9-bootc:kioskv2
      applications:
        - appType: container
          envVars: {}
          image: quay.io/alitestseverything/product-api:v1
          name: product-api
          ports:
            - '3000:3000'
      config:
        - name: "silence-audit-logs"
          inline:
            - path: "/etc/sysctl.d/20-quiet-printk.conf"
              content: "kernel.printk = 3 4 1 3"
              mode: 0644
        # STEP 1: Force the creation of the writable directory via tmpfiles
        # - name: prep-writable-storage
        #   inline:
        #     - path: "/etc/tmpfiles.d/kiosk.conf"
        #       content: |
        #         d /var/www 0755 root root -
        #         d /var/www/html 0755 root root -
        #         d /etc/flightctl/hooks.d/afterupdating 0755 root root -
        #       mode: 0644
        - name: prep-writable-storage
          inline:
            - path: "/etc/tmpfiles.d/kiosk.conf"
              content: |
                d /etc/flightctl/hooks.d/afterupdating 0755 root root -
              mode: 0644
        - name: kiosk-refresh-hook
          inline:
            - path: /etc/flightctl/hooks.d/afterupdating/10-refresh-browser.yaml
              content: |
                - run: /usr/local/bin/kiosk-refresh.sh
                  if:
                    - path: /var/lib/kiosk/html
                      op: [created, updated, deleted]
        # - name: gdm-restart-hook
        #   inline:
        #     - path: /etc/flightctl/hooks.d/afterupdating/11-restart-gdm.yaml
        #       content: |-
        #         - run: /usr/bin/systemctl restart gdm
        #           timeout: 10s
        #           if:
        #             - path: /var/lib/kiosk/html
        #               op: [created, updated, deleted]
        - name: motd-update
          inline:
            - path: "/etc/motd"
              content: "This system is managed by flightctl."
              mode: 0644
        - name: kioskapp
          configType: GitConfigProviderSpec
          gitRef:
            repository: rhem-default
            targetRevision: main
            path: /rhem/kiosk
      resources:
        - monitorType: CPU
          alertRules:
            - severity: Warning
              duration: 10m
              percentage: 70
              description: 'CPU load is above 50% for more than 10 minutes'
          samplingInterval: 30s
      systemd:
        matchPatterns:
          - chronyd.service